### ISSUE TITLE
Question array --> create new child record for each question in array

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Nalibali#1]
**Request:**
- Map each question to 1 new **Every1Mobile_Activity__c** record
- I tried implementing the `each()` function to upsert 1 **Every1Mobile_Activity__c** record for each question in the `questions[]` array, but I'm hitting the error `TypeError: Cannot read property 'survey' of undefined`. 
- I suspect this undefined error has something to do with `dataPath()` and [L22](https://github.com/OpenFn/Nalibali/blob/master/add-survey.js#L22) where I reference `state.data.payload.user_id` that does _not_ fall within `dataPath(state.data.payload.survey.questions[*])`.

This same fix needs to be applied in **2 jobs**. See affected Lines linked to below: 
1. [add-survey.js ](https://github.com/OpenFn/Nalibali/blob/a0efa431bd48e304f59b7fcffebdb9e1200aaf1b/add-survey.js#L16-L17)
2. [add-quiz.js](https://github.com/OpenFn/Nalibali/blob/a0efa431bd48e304f59b7fcffebdb9e1200aaf1b/add-quiz.js#L16-L18)

**`state.json`** files to run: 
1. [quiz.json](https://github.com/OpenFn/Nalibali/blob/master/sample_data/quiz.json)
2. [survey.json](https://github.com/OpenFn/Nalibali/blob/master/sample_data/survey.json)

**Creds:** see LastPass
**Toggl:** https://toggl.com/app/3335160/projects/155848661/team

**Comment by taylordowns2000** [comment]
https://openfn.github.io/docs/documentation.html#merge-many-values-into-a-child-path -- this will do it. change coming.
