### ISSUE TITLE
Quiz.js and Survey.js fail on upsert

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Nalibali#2]
https://github.com/OpenFn/Nalibali/blob/38528f1bce5708146ababdf2497be50c3c38f116/add-survey.js#L14-L18

On both `quiz.js` and `survey.js`, I am hitting an **error when testing the upsert functionality**: 
`{ INVALID_FIELD_FOR_INSERT_UPDATE: Unable to create/update fields: Contact__c. Please check the security settings of this field and verify that it is read/write for your profile or permission set.`

**Steps to replicate:** 
1. Run `survey.js` against `survey.json` --> Successful run, will insert multiple E1M Activity records 
2. Re-run the same files to upsert records created in prior step --> 
- _Actual Behavior:_  FAILED run with above `INVALID_FIELD_FOR_INSERT_UPDATE` error 
- _Expected Behavior:_ Successful run, should upsert records inserted in step #1

3. If I delete the records created in #1, and then repeat these steps --> 
- Step # 1 succeeds --> able to newly insert the E1M Activity records
- Step # 2 upsert fails --> I hit the same error 

**Question: Why do these jobs fail on _upsert_?**
- This works fine with Salesforce.FakeAdaptor
- I have confirmed that the parent Contact record exists with the matching `Every1Mobile_ID__c: 10398529`: https://nalibali--ofnsand.lightning.force.com/lightning/r/Contact/0030E00000dYwUBQA0/view
- I checked Workbench to confirm that that `Contact__r` is the correct relationship field API name (also the job should fail on insert if this was incorrect)

**Creds:** see LastPass
**Toggl:** https://toggl.com/app/3335160/projects/155848661/team

**Comment by aleksa-krolls** [comment]
@taylordowns2000 I'm stumped on this one... the upsert succeeds on FakeAdaptor. Wondering if there's maybe something going on the API version/ JSforce?

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this smells like a master-detail that's not reparentable!
